---
- name: Helm install cloudpg repo
  command: helm repo add {{ item.name }} {{ item.url }}
  with_items: "{{ repos }}"

# - name: Helm install cloudpg repo
#   command: helm repo add cloudpg https://cloud-pg.github.io/charts/ 

# - name: Helm install cache repos
#   command: helm repo add cache https://cloud-pg.github.io/CachingOnDemand/

- name: write values
  lineinfile:
    dest:  /tmp/values_{{ name }}.yml
    create: yes
    line: "{{ item }}"
  with_items: 
    - "{{ values_file.split('\n') }}"

- name: Helm install chart {{ chart }}
  command: "helm install --name {{ name }} -f /tmp/values_{{ name }}.yml {{ chart }}"
